dist: xenial
language: python
python:
  - '3.7'
  - 3.7-dev
  - 3.8-dev
matrix:
  allow_failures:
  - python: 3.8-dev
  - python: 3.7-dev
  fast_finish: true
install:
- pip install -U pip setuptools wheel
- pip install tox-travis
- pip install .
script:
- tox
deploy:
  provider: pypi
  user: loicgrobol
  password:
    secure: NRM1ds0Zt9lFVyi5HlpEx1idimHEBMhfTwiciJ0voECL+qaZPZR3fkxFv1vK+8J2gPAzGS7R2mwWzh8DYgX8KTjL+6yMxUqctRBOw2yhjhd/7UdUDcUf9KN82jFVlAY36PQWXXrS5ezOVEwTK/7IUylKtnSQsMByPbaPd3S1RkxAL/brnEZv17rCd7b0Vm224S+4gjntxpSXJp3tcZsWF/bgKdZVTZJtEbzR7vZRUxpdnAb1MZ6GrxpRiItOAoyxfMqNXtkq/Q/NpBXDWYFBFH3Rzp+WAgk2PS0uIPB4gXOJ2ht7KUoYbEnKv/EtY+xzzHdABJt/6vXo8TYIv0W89XAx/p2k/CG0H98iki8nqGeQqbbb4rhUYk/aqLHizuuGXJE4vidaYfkpDDAPSa2+ieWZwx2j/BduEHydihNcP7Wd0QSffH7AfhwDLFkI3mbt5krAK/hL7XzxNUK0cr9aLb/IDuxpg3UDSKYqG4F+PkdMdkUt7ZktH1fI3+CG/3Bg5jWKXUBv8iKwAh+9E2EEML4/x3njPtyfU8YpjVvVx5u3tgHz2lw5d/D0UAgZsm7QeO7qJQLB+IrCr5jPDp1QGpCV5Cg6H3rCo4u3nW9spfhKZEYXkxoPOBflKjsOQFw4cv/3mMUn9lpgg1Skf+eDJxnxoPnzPUzyW2X+xL0JI7w=
  on:
    tags: true
    python: '3.7'
  distributions: sdist bdist_wheel
  skip_existing: true
