[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 88
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.virtenv
  | \.ropeproject
  | _build
  | build
  | dist
)/
'''
